"""The catalogue of reports this package can render.

In the workshop the catalogue lives in ``catalog/reports.yaml`` and is regenerated by
``tools/catalog.py``, which scrapes the two live sars.ac.tz listing pages. Neither the YAML file
nor the scraper is shipped: the runtime reads a distilled ``reports.json`` copied into the
package at build time, so an installed package needs no YAML parser and never touches the
network.

Report keys are snake_case and unique per level, and a handful of keys exist at both levels (for
example ``school_results`` is a secondary report and a primary one). :func:`find` therefore
accepts an optional level and only insists on one when the key alone is ambiguous.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache

from .errors import UnknownReportError
from .resources import artifact_name, registry_payload

LEVELS = ("primary", "secondary")


@dataclass(frozen=True, slots=True)
class Report:
    """One renderable report.

    Attributes:
        level: ``"primary"`` or ``"secondary"``.
        report_key: The snake_case identifier, unique within a level.
        title: The report's heading as it appears on the reference PDF.
        scope: What the report covers — ``school``, ``council``, ``region`` or ``subject``.
        sample_unit: The unit the reference PDF was measured from, e.g. a school name. Useful as
            a placeholder but not part of the data contract.
        ordinal: Position in the workshop's processing order, 1-46.
    """

    level: str
    report_key: str
    title: str
    scope: str
    sample_unit: str
    ordinal: int

    @property
    def identity(self) -> str:
        """The kebab-case directory name used for this report's packaged resources."""
        return artifact_name(self.report_key)


@lru_cache(maxsize=1)
def _reports() -> tuple[Report, ...]:
    payload = registry_payload()
    return tuple(
        Report(
            level=entry["level"],
            report_key=entry["report_key"],
            title=entry["title"],
            scope=entry["scope"],
            sample_unit=entry.get("sample_unit", ""),
            ordinal=entry["ordinal"],
        )
        for entry in payload["reports"]
    )


def list_reports(level: str | None = None) -> list[Report]:
    """Every report the package can render, in the workshop's processing order.

    Args:
        level: Restrict to ``"primary"`` or ``"secondary"``. ``None`` returns both.

    Raises:
        UnknownReportError: If ``level`` is not a known level.
    """
    reports = _reports()
    if level is None:
        return sorted(reports, key=lambda report: report.ordinal)
    if level not in LEVELS:
        raise UnknownReportError(f"Unknown level {level!r}; choose from {list(LEVELS)}")
    return sorted((r for r in reports if r.level == level), key=lambda report: report.ordinal)


def find(report_key: str, level: str | None = None) -> Report:
    """Look up one report.

    Args:
        report_key: The snake_case report key. Kebab-case is accepted too, so the identity used
            for directory names round-trips.
        level: Required only when the key exists at both levels.

    Raises:
        UnknownReportError: If nothing matches, or if the key is ambiguous and no level was given.
    """
    key = report_key.replace("-", "_")
    matches = [r for r in _reports() if r.report_key == key]
    if level is not None:
        if level not in LEVELS:
            raise UnknownReportError(f"Unknown level {level!r}; choose from {list(LEVELS)}")
        matches = [r for r in matches if r.level == level]

    if not matches:
        where = f" at level {level!r}" if level else ""
        raise UnknownReportError(
            f"Unknown report {report_key!r}{where}. "
            f"Call mussannoni.list_reports() for the {len(_reports())} available reports."
        )
    if len(matches) > 1:
        levels = sorted(r.level for r in matches)
        raise UnknownReportError(
            f"Report {report_key!r} exists at levels {levels}; pass level= to choose one."
        )
    return matches[0]
