"""Sync the workshop's measured artifacts into the installable package.

The workshop measures reports into ``templates/``; the package renders them from
``src/mussannoni/resources/``. This module is the bridge, and it is a build step rather than a
runtime one so that an installed package never depends on the repository layout.

What crosses over, and what does not:

- ``template.html`` — one copy. All 46 are byte-identical and this asserts that before relying
  on it.
- ``_shared/reset.css`` and ``_shared/fonts/`` — verbatim.
- per report: ``report.css`` and ``fonts/`` verbatim, plus a distilled ``layout.json``.
- ``reports.json`` — the registry, distilled from ``catalog/reports.yaml``.
- **Not** ``fixture.json``. The 46 fixtures are 257 MB of measured geometry for one sample unit
  each. They are sample data, they cannot be authored by a caller, and shipping them would make
  the wheel unusable. Everything a caller actually needs from a fixture — the page box, the
  column grid, the header band, the body row shape — is distilled into ``layout.json``, which
  comes to a few KB.

Run with ``python -m tools.package_resources`` (or ``make package-resources``). ``--check``
verifies the committed resources are current without writing, which is what CI and the test
suite use.
"""

from __future__ import annotations

import argparse
import filecmp
import json
import re
import shutil
from collections import Counter
from pathlib import Path
from typing import Any

from tools.common import ROOT, artifact_name, load_catalog, template_dir, write_json

PACKAGE_DIR = ROOT / "src" / "mussannoni"
RESOURCE_DIR = PACKAGE_DIR / "resources"
SHARED_SOURCE = ROOT / "templates" / "_shared"

LAYOUT_SCHEMA_VERSION = 1

# Which base-14 face MuPDF measures a font stack with. The stacks are generated by
# tools/fonts.py BASE14_MAP, so these are the only ones that appear in a report.css.
BASE14_BY_STACK = {
    ("Arial, 'Report Sans'", 400, "normal"): "helv",
    ("Arial, 'Report Sans'", 700, "normal"): "hebo",
    ("Arial, 'Report Sans'", 400, "italic"): "heit",
    ("Arial, 'Report Sans'", 700, "italic"): "hebi",
    ("'Times New Roman', 'Report Serif'", 400, "normal"): "tiro",
    ("'Times New Roman', 'Report Serif'", 700, "normal"): "tibo",
    ("'Times New Roman', 'Report Serif'", 400, "italic"): "tiro",
    ("'Report Mono'", 400, "normal"): "cour",
}

TEXT_RULE = re.compile(r"\.(t\d+)\s*\{([^}]*)\}")
FONT_FACE_RULE = re.compile(r"@font-face\s*\{([^}]*)\}", re.DOTALL)
DECLARATION = re.compile(r"([a-z-]+)\s*:\s*([^;]+)")


def _declarations(block: str) -> dict[str, str]:
    return {name: value.strip() for name, value in DECLARATION.findall(block)}


def parse_text_styles(css: str) -> dict[str, dict[str, Any]]:
    """Map each ``.tN`` class to the size and the face needed to measure its advance widths.

    The table API places generated text by computing where it ends up, which means it has to
    measure the string. A class backed by a font embedded in the reference PDF is measured with
    that font file; a class backed by a named system face (Arial, Times) is measured with the
    base-14 face MuPDF substitutes, which is the same face the shipped fallback exports.
    """
    embedded: dict[str, str] = {}
    for block in FONT_FACE_RULE.findall(css):
        declarations = _declarations(block)
        family = declarations.get("font-family", "").strip("'\"")
        source = declarations.get("src", "")
        match = re.search(r"url\(['\"]?([^'\")]+)", source)
        if family and match:
            embedded[family] = match.group(1)

    styles: dict[str, dict[str, Any]] = {}
    for name, block in TEXT_RULE.findall(css):
        declarations = _declarations(block)
        stack = declarations.get("font-family", "").strip()
        size = float(declarations.get("font-size", "0pt").removesuffix("pt"))
        weight = int(declarations.get("font-weight", "400"))
        style = declarations.get("font-style", "normal")

        entry: dict[str, Any] = {"size_pt": size, "font_family": stack}
        bare = stack.strip("'\"")
        if bare in embedded:
            entry["fontfile"] = embedded[bare]
        else:
            entry["base14"] = BASE14_BY_STACK.get((stack, weight, style), "helv")
        styles[name] = entry
    return styles


SEGMENT = re.compile(
    r"M(-?\d*\.?\d+) (-?\d*\.?\d+)h(-?\d*\.?\d+)v(-?\d*\.?\d+)h(-?\d*\.?\d+)Z"
)


def _hairline(
    rules: list[dict[str, Any]], table_y: float, header_height: float
) -> dict[str, Any] | None:
    """The gridline weight and colour, plus the header band's rules kept verbatim.

    Gridlines are drawn as filled hairline rectangles, so each one appears as
    ``M<x> <y>h<w>v<h>h-<w>Z`` and the narrower of ``w``/``h`` is the stroke weight.

    The body's rules have to be redrawn for whatever number of rows the caller supplies, but the
    header band's cannot be synthesised: its cells are merged into subject groups, so drawing
    every column boundary across it would strike lines through the merged headings. The segments
    that lie wholly inside the header band are therefore kept exactly as measured, and only the
    body band is regenerated.
    """
    if not rules:
        return None
    path = rules[0].get("d", "")
    segments = SEGMENT.findall(path)
    if not segments:
        return None

    weights: list[float] = []
    header_segments: list[str] = []
    header_bottom = table_y + header_height + 0.5

    for x, y, width, height, _ in segments:
        w, h = abs(float(width)), abs(float(height))
        if w > 0 and h > 0:
            weights.append(min(w, h))
        if float(y) + h <= header_bottom:
            header_segments.append(f"M{x} {y}h{width}v{height}h{_}Z")

    if not weights:
        return None
    return {
        "width_pt": min(weights),
        "fill": rules[0].get("fill", "color(srgb 0 0 0)"),
        "header_d": "".join(header_segments),
    }


def _body_prototype(pages: list[dict[str, Any]], header_rows: int) -> dict[str, Any] | None:
    """The shape of a plain body row: its height, and each column's cell styling.

    Distilled by taking the most common value seen across every body row of every page, so a
    report's occasional sub-heading or total band does not become the prototype. Cells that span
    are skipped: a span is structure, not a repeating row shape.
    """
    heights: Counter[float] = Counter()
    per_column: dict[int, Counter[str]] = {}

    for page in pages:
        for row in page["rows"][header_rows:]:
            heights[round(float(row["height_pt"]), 2)] += 1
            for cell in row["cells"]:
                if cell.get("colspan", 1) != 1 or cell.get("rowspan", 1) != 1:
                    continue
                lines = cell.get("lines") or []
                if not lines:
                    continue
                line = lines[0]
                runs = line.get("runs") or []
                shape = {
                    "classes": cell.get("classes", []),
                    "align": cell.get("align", "left"),
                    "pad_left": cell.get("pad_left", 0.0),
                    "pad_right": cell.get("pad_right", 0.0),
                    "line_class": line.get("class", "t0"),
                    "top_pt": line.get("top_pt", 0.0),
                    "rotation": line.get("rotation", 0),
                    "run_class": runs[0].get("class", line.get("class", "t0")) if runs else
                    line.get("class", "t0"),
                }
                bucket = per_column.setdefault(int(cell["column"]), Counter())
                bucket[json.dumps(shape, sort_keys=True)] += 1

    if not heights or not per_column:
        return None

    row_height = heights.most_common(1)[0][0]
    cells = [
        json.loads(bucket.most_common(1)[0][0]) | {"column": column}
        for column, bucket in sorted(per_column.items())
    ]
    return {"row_height_pt": row_height, "cells": cells}


def _rows_per_page(pages: list[dict[str, Any]], header_rows: int, row_height: float) -> int:
    """How many plain body rows fit, from the tallest body band actually measured."""
    tallest = 0.0
    for page in pages:
        band = sum(float(row["height_pt"]) for row in page["rows"][header_rows:])
        tallest = max(tallest, band)
    if row_height <= 0:
        return 1
    return max(1, int(tallest // row_height))


def _column_labels(header: list[dict[str, Any]], column_count: int) -> list[str]:
    """The column labels, read from the lowest header row that names most of the columns."""
    best: list[str] = [""] * column_count
    best_filled = -1
    for row in header:
        labels = [""] * column_count
        for cell in row["cells"]:
            column = int(cell["column"])
            if column >= column_count:
                continue
            text = " ".join(
                run.get("text", "")
                for line in cell.get("lines") or []
                for run in line.get("runs") or []
            ).strip()
            if text:
                labels[column] = text
        filled = sum(1 for label in labels if label)
        if filled > best_filled:
            best, best_filled = labels, filled
    return best


def distil_layout(report: dict[str, Any], fixture: dict[str, Any], css: str) -> dict[str, Any]:
    """Reduce a measured fixture to the layout a caller's data can be placed onto."""
    pages = fixture["pages"]
    first = pages[0]
    header_rows = int(first["header_rows"])
    header = [dict(row) for row in first["rows"][:header_rows]]
    columns = [float(width) for width in first["columns"]]

    prototype = _body_prototype(pages, header_rows)
    layout: dict[str, Any] = {
        "schema_version": LAYOUT_SCHEMA_VERSION,
        "level": report["level"],
        "report_key": report["report_key"],
        "title": fixture["report"].get("title", report.get("title", "")),
        "scope": report.get("scope", ""),
        "sample_unit": fixture["report"].get("sample_unit", ""),
        "page": {
            "width_pt": float(first["width_pt"]),
            "height_pt": float(first["height_pt"]),
            "orientation": first["orientation"],
        },
        "table": {
            "x_pt": float(first["table_x_pt"]),
            "y_pt": float(first["table_y_pt"]),
            "width_pt": float(first["table_width_pt"]),
            "columns": columns,
        },
        "header": {
            "row_count": header_rows,
            "rows": header,
            "height_pt": round(sum(float(row["height_pt"]) for row in header), 3),
            "labels": _column_labels(header, len(columns)),
        },
        "text_styles": parse_text_styles(css),
        "rule": _hairline(
            first.get("rules") or [],
            float(first["table_y_pt"]),
            sum(float(row["height_pt"]) for row in header),
        ),
        "decorations": {
            "vectors": first.get("vectors") or [],
            "loose_lines": first.get("loose_lines") or [],
        },
        "measured_pages": len(pages),
    }
    if prototype:
        layout["body"] = prototype
        layout["rows_per_page"] = _rows_per_page(pages, header_rows, prototype["row_height_pt"])
    else:
        # A report with no plain repeating body row (every band spans or is styled differently)
        # cannot be driven by the table API. Say so in the data rather than guessing a shape.
        layout["body"] = None
        layout["rows_per_page"] = 0
    return layout


def _sync_tree(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for child in sorted(source.iterdir()):
        if child.is_dir():
            continue
        target = destination / child.name
        if not target.exists() or not filecmp.cmp(child, target, shallow=False):
            shutil.copy2(child, target)


def build(check: bool = False) -> list[str]:
    """Regenerate every packaged resource. Returns a list of human-readable differences.

    With ``check=True`` nothing is written and the differences are reported instead, so the test
    suite can fail when the committed resources have drifted from the workshop.
    """
    if check:
        return _check()

    catalog = load_catalog()
    reports = catalog["reports"]
    RESOURCE_DIR.mkdir(parents=True, exist_ok=True)

    # One template for all 46. Assert that before relying on it.
    templates = {
        (template_dir(report) / "template.html").read_bytes()
        for report in reports
        if (template_dir(report) / "template.html").exists()
    }
    if len(templates) != 1:
        raise RuntimeError(
            f"Expected one shared template.html across all reports, found {len(templates)} "
            "distinct versions. The package ships a single copy, so they must not diverge."
        )
    (RESOURCE_DIR / "template.html").write_bytes(templates.pop())

    (RESOURCE_DIR / "_shared").mkdir(parents=True, exist_ok=True)
    shutil.copy2(SHARED_SOURCE / "reset.css", RESOURCE_DIR / "_shared" / "reset.css")
    _sync_tree(SHARED_SOURCE / "fonts", RESOURCE_DIR / "_shared" / "fonts")

    registry = {
        "schema_version": 1,
        "sources": catalog.get("sources", {}),
        "reports": [
            {
                "ordinal": report["ordinal"],
                "level": report["level"],
                "report_key": report["report_key"],
                "title": report["title"],
                "scope": report["scope"],
                "sample_unit": report.get("sample_unit", ""),
            }
            for report in sorted(reports, key=lambda item: item["ordinal"])
        ],
    }
    write_json(RESOURCE_DIR / "reports.json", registry)

    for report in reports:
        source = template_dir(report)
        destination = RESOURCE_DIR / report["level"] / artifact_name(report["report_key"])
        destination.mkdir(parents=True, exist_ok=True)

        css_path = source / "report.css"
        shutil.copy2(css_path, destination / "report.css")
        if (source / "fonts").is_dir():
            _sync_tree(source / "fonts", destination / "fonts")

        fixture_path = source / "fixture.json"
        if not fixture_path.exists():
            continue
        fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
        layout = distil_layout(report, fixture, css_path.read_text(encoding="utf-8"))
        write_json(destination / "layout.json", layout)

    return []


def _check() -> list[str]:
    """Rebuild into a scratch tree and diff it against the committed resources."""
    import tempfile

    global RESOURCE_DIR
    committed = RESOURCE_DIR
    with tempfile.TemporaryDirectory(prefix="mussannoni-resource-check-") as raw:
        RESOURCE_DIR = Path(raw) / "resources"
        try:
            build(check=False)
            fresh = RESOURCE_DIR
        finally:
            RESOURCE_DIR = committed

        differences: list[str] = []
        fresh_files = {p.relative_to(fresh) for p in fresh.rglob("*") if p.is_file()}
        committed_files = {
            p.relative_to(committed) for p in committed.rglob("*") if p.is_file()
        }
        for missing in sorted(fresh_files - committed_files):
            differences.append(f"missing from package resources: {missing}")
        for extra in sorted(committed_files - fresh_files):
            differences.append(f"stale in package resources: {extra}")
        for shared in sorted(fresh_files & committed_files):
            if not filecmp.cmp(fresh / shared, committed / shared, shallow=False):
                differences.append(f"out of date in package resources: {shared}")
        return differences


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the committed package resources are current, writing nothing",
    )
    args = parser.parse_args()

    differences = build(check=args.check)
    if args.check:
        if differences:
            print(f"package resources are out of date ({len(differences)} differences):")
            for difference in differences[:20]:
                print(f"  {difference}")
            if len(differences) > 20:
                print(f"  ... and {len(differences) - 20} more")
            raise SystemExit(1)
        print("package resources are current")
    else:
        count = sum(1 for _ in RESOURCE_DIR.rglob("*") if _.is_file())
        print(f"synced {count} files into {RESOURCE_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
