"""Sync the workshop's measured artifacts into the installable package.

The workshop measures reports into ``templates/``; the package renders them from
``src/mussannoni/resources/``. This module is the bridge, and it is a build step rather than a
runtime one so that an installed package never depends on the repository layout.

What crosses over, and what does not:

- ``template.html`` — one copy. All 46 are byte-identical and this asserts that before relying
  on it.
- ``_shared/reset.css`` and ``_shared/fonts/`` — verbatim.
- per report: ``report.css`` and ``fonts/`` verbatim, plus a distilled ``layout.json``.
- ``reports.json`` — the registry, distilled from ``catalog/reports.yaml``.
- **Not** ``fixture.json``. The 46 fixtures are 257 MB of measured geometry for one sample unit
  each. They are sample data, they cannot be authored by a caller, and shipping them would make
  the wheel unusable. Everything a caller actually needs from a fixture — the page box, the
  column grid, the header band, the body row shape — is distilled into ``layout.json``, which
  comes to a few KB.

Run with ``python -m tools.package_resources`` (or ``make package-resources``). ``--check``
verifies the committed resources are current without writing, which is what CI and the test
suite use.
"""

from __future__ import annotations

import argparse
import filecmp
import gzip
import json
import re
import shutil
from collections import Counter
from copy import deepcopy
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

from tools.common import ROOT, artifact_name, load_catalog, template_dir, write_json

PACKAGE_DIR = ROOT / "src" / "mussannoni"
RESOURCE_DIR = PACKAGE_DIR / "resources"
SHARED_SOURCE = ROOT / "templates" / "_shared"
BINDINGS_CATALOG = ROOT / "catalog" / "bindings.yaml"

LAYOUT_SCHEMA_VERSION = 2

# Which base-14 face MuPDF measures a font stack with. The stacks are generated by
# tools/fonts.py BASE14_MAP, so these are the only ones that appear in a report.css.
BASE14_BY_STACK = {
    ("Arial, 'Report Sans'", 400, "normal"): "helv",
    ("Arial, 'Report Sans'", 700, "normal"): "hebo",
    ("Arial, 'Report Sans'", 400, "italic"): "heit",
    ("Arial, 'Report Sans'", 700, "italic"): "hebi",
    ("'Times New Roman', 'Report Serif'", 400, "normal"): "tiro",
    ("'Times New Roman', 'Report Serif'", 700, "normal"): "tibo",
    ("'Times New Roman', 'Report Serif'", 400, "italic"): "tiro",
    ("'Report Mono'", 400, "normal"): "cour",
}

TEXT_RULE = re.compile(r"\.(t\d+)\s*\{([^}]*)\}")
FONT_FACE_RULE = re.compile(r"@font-face\s*\{([^}]*)\}", re.DOTALL)
DECLARATION = re.compile(r"([a-z-]+)\s*:\s*([^;]+)")


def _declarations(block: str) -> dict[str, str]:
    return {name: value.strip() for name, value in DECLARATION.findall(block)}


def parse_text_styles(css: str) -> dict[str, dict[str, Any]]:
    """Map each ``.tN`` class to the size and the face needed to measure its advance widths.

    The table API places generated text by computing where it ends up, which means it has to
    measure the string. A class backed by a font embedded in the reference PDF is measured with
    that font file; a class backed by a named system face (Arial, Times) is measured with the
    base-14 face MuPDF substitutes, which is the same face the shipped fallback exports.
    """
    embedded: dict[str, str] = {}
    for block in FONT_FACE_RULE.findall(css):
        declarations = _declarations(block)
        family = declarations.get("font-family", "").strip("'\"")
        source = declarations.get("src", "")
        match = re.search(r"url\(['\"]?([^'\")]+)", source)
        if family and match:
            embedded[family] = match.group(1)

    styles: dict[str, dict[str, Any]] = {}
    for name, block in TEXT_RULE.findall(css):
        declarations = _declarations(block)
        stack = declarations.get("font-family", "").strip()
        size = float(declarations.get("font-size", "0pt").removesuffix("pt"))
        weight = int(declarations.get("font-weight", "400"))
        style = declarations.get("font-style", "normal")

        entry: dict[str, Any] = {"size_pt": size, "font_family": stack}
        bare = stack.strip("'\"")
        if bare in embedded:
            entry["fontfile"] = embedded[bare]
        else:
            entry["base14"] = BASE14_BY_STACK.get((stack, weight, style), "helv")
        styles[name] = entry
    return styles


SEGMENT = re.compile(
    r"M(-?\d*\.?\d+) (-?\d*\.?\d+)h(-?\d*\.?\d+)v(-?\d*\.?\d+)h(-?\d*\.?\d+)Z"
)


def _hairline(
    rules: list[dict[str, Any]], table_y: float, header_height: float
) -> dict[str, Any] | None:
    """The gridline weight and colour, plus the header band's rules kept verbatim.

    Gridlines are drawn as filled hairline rectangles, so each one appears as
    ``M<x> <y>h<w>v<h>h-<w>Z`` and the narrower of ``w``/``h`` is the stroke weight.

    The body's rules have to be redrawn for whatever number of rows the caller supplies, but the
    header band's cannot be synthesised: its cells are merged into subject groups, so drawing
    every column boundary across it would strike lines through the merged headings. The segments
    that lie wholly inside the header band are therefore kept exactly as measured, and only the
    body band is regenerated.
    """
    if not rules:
        return None
    path = rules[0].get("d", "")
    segments = SEGMENT.findall(path)
    if not segments:
        return None

    weights: list[float] = []
    header_segments: list[str] = []
    header_bottom = table_y + header_height + 0.5

    for x, y, width, height, _ in segments:
        w, h = abs(float(width)), abs(float(height))
        if w > 0 and h > 0:
            weights.append(min(w, h))
        if float(y) + h <= header_bottom:
            header_segments.append(f"M{x} {y}h{width}v{height}h{_}Z")

    if not weights:
        return None
    return {
        "width_pt": min(weights),
        "fill": rules[0].get("fill", "color(srgb 0 0 0)"),
        "header_d": "".join(header_segments),
    }


def _body_prototype(pages: list[dict[str, Any]], header_rows: int) -> dict[str, Any] | None:
    """The shape of a plain body row: its height, and each column's cell styling.

    Distilled by taking the most common value seen across every body row of every page, so a
    report's occasional sub-heading or total band does not become the prototype. Cells that span
    are skipped: a span is structure, not a repeating row shape.
    """
    heights: Counter[float] = Counter()
    per_column: dict[int, Counter[str]] = {}

    for page in pages:
        for row in page["rows"][header_rows:]:
            heights[round(float(row["height_pt"]), 2)] += 1
            for cell in row["cells"]:
                if cell.get("colspan", 1) != 1 or cell.get("rowspan", 1) != 1:
                    continue
                lines = cell.get("lines") or []
                if not lines:
                    continue
                line = lines[0]
                runs = line.get("runs") or []
                shape = {
                    "classes": cell.get("classes", []),
                    "align": cell.get("align", "left"),
                    "pad_left": cell.get("pad_left", 0.0),
                    "pad_right": cell.get("pad_right", 0.0),
                    "line_class": line.get("class", "t0"),
                    "top_pt": line.get("top_pt", 0.0),
                    "rotation": line.get("rotation", 0),
                    "run_class": runs[0].get("class", line.get("class", "t0")) if runs else
                    line.get("class", "t0"),
                }
                bucket = per_column.setdefault(int(cell["column"]), Counter())
                bucket[json.dumps(shape, sort_keys=True)] += 1

    if not heights or not per_column:
        return None

    row_height = heights.most_common(1)[0][0]
    cells = [
        json.loads(bucket.most_common(1)[0][0]) | {"column": column}
        for column, bucket in sorted(per_column.items())
    ]
    return {"row_height_pt": row_height, "cells": cells}


def _rows_per_page(pages: list[dict[str, Any]], header_rows: int, row_height: float) -> int:
    """How many plain body rows fit, from the tallest body band actually measured."""
    tallest = 0.0
    for page in pages:
        band = sum(float(row["height_pt"]) for row in page["rows"][header_rows:])
        tallest = max(tallest, band)
    if row_height <= 0:
        return 1
    return max(1, int(tallest // row_height))


def _column_labels(header: list[dict[str, Any]], column_count: int) -> list[str]:
    """The column labels, read from the lowest header row that names most of the columns."""
    best: list[str] = [""] * column_count
    best_filled = -1
    for row in header:
        labels = [""] * column_count
        for cell in row["cells"]:
            column = int(cell["column"])
            if column >= column_count:
                continue
            text = " ".join(
                run.get("text", "")
                for line in cell.get("lines") or []
                for run in line.get("runs") or []
            ).strip()
            if text:
                labels[column] = text
        filled = sum(1 for label in labels if label)
        if filled > best_filled:
            best, best_filled = labels, filled
    return best


def _column_edges(widths: list[float]) -> list[float]:
    """Cumulative left edges of a column grid, plus its right edge."""
    edges = [0.0]
    for width in widths:
        edges.append(round(edges[-1] + width, 2))
    return edges


def _remap_row(row: dict[str, Any], source_widths: list[float],
               target_widths: list[float]) -> dict[str, Any] | None:
    """One measured row moved from a finer column grid onto a coarser one.

    A page that carries two tables is measured on the union of both grids, so its columns
    subdivide the grid the body pages repeat: ``school-results`` measures 11 columns on page 1
    where the candidate rows use 9, the extra two being splits of the name and subjects columns.
    Because the coarse grid's edges are a subset of the fine one's, every cell can be placed by
    matching its left and right edge, which is what this does. Returns ``None`` if any cell does
    not align, so a grid that is not a subdivision is refused rather than approximated.
    """
    source_edges = _column_edges(source_widths)
    target_edges = _column_edges(target_widths)

    def index_of(edge: float) -> int | None:
        for position, value in enumerate(target_edges):
            if abs(value - edge) < 0.05:
                return position
        return None

    remapped: list[dict[str, Any]] = []
    for cell in row["cells"]:
        start = int(cell["column"])
        span = int(cell.get("colspan", 1) or 1)
        if start >= len(source_edges) - 1:
            return None
        left = index_of(source_edges[start])
        right = index_of(source_edges[min(start + span, len(source_edges) - 1)])
        if left is None or right is None or right <= left:
            # A cell whose boundaries are interior to a target column cannot be placed.
            continue
        moved = dict(cell)
        moved["column"] = left
        moved["colspan"] = right - left
        remapped.append(moved)
    if not remapped:
        return None
    moved_row = dict(row)
    moved_row["cells"] = remapped
    return moved_row


def _is_label_row(row: dict[str, Any]) -> bool:
    """Whether a measured row labels its table rather than carrying data.

    A label row names several columns, each with a word rather than a figure. Counted per cell,
    not per line: the letterhead is a single wide cell holding many lines and must not be mistaken
    for a label band.
    """
    cell_texts: list[str] = []
    for cell in row["cells"]:
        joined = " ".join(text.strip() for text in _cell_texts(cell) if text.strip())
        if joined:
            cell_texts.append(joined)
    if len(cell_texts) < 3:
        return False
    return not any(_NUMERIC.match(text) for text in cell_texts)


def _cell_texts(cell: dict[str, Any]) -> list[str]:
    return [
        "".join(run.get("text", "") for run in (line.get("runs") or []))
        for line in (cell.get("lines") or [])
    ]


_NUMERIC = re.compile(r"^-?\d+(?:[.,]\d+)?%?$")


def _transplanted_header(source: dict[str, Any],
                         target_widths: list[float]) -> list[dict[str, Any]]:
    """The header band for a repeating grid, taken from a compound first page.

    When the body pages' own ``header_rows`` marks a data row — a continuation page has no
    repeating label band of its own — the band has to come from the page that does carry it. Two
    rows are taken: the letterhead, and the row that labels the repeating table's columns. Both
    are remapped onto the repeating grid.
    """
    source_widths = [float(width) for width in source["columns"]]
    rows = source["rows"]

    letterhead = rows[0] if rows else None
    label_row = None
    for row in rows:
        if _is_label_row(row):
            label_row = row
            break

    band: list[dict[str, Any]] = []
    for candidate in (letterhead, label_row):
        if candidate is None:
            continue
        moved = _remap_row(candidate, source_widths, target_widths)
        if moved is not None:
            band.append(moved)
    return band


def _spanning_prototype(rows: list[dict[str, Any]]) -> dict[str, Any] | None:
    """The shape of a band's own data row, with spans kept.

    :func:`_body_prototype` deliberately skips spanning cells, because on a repeating grid a span
    is structure rather than a row shape. A compound first page is the opposite case: its data
    rows sit on the *union* grid, where the name and subjects columns really are spans, so a
    prototype without them would have no cell to put those values in.

    Taken from the modal ``(column, colspan)`` signature so an occasional short row does not
    become the prototype, and a cell the measurement only ever saw empty still gets a shape —
    borrowed from the band's other cells — rather than being dropped and silently swallowing a
    caller's value.
    """
    if not rows:
        return None

    def signature(row: dict[str, Any]) -> tuple[tuple[int, int], ...]:
        return tuple(
            (int(cell["column"]), int(cell.get("colspan", 1) or 1)) for cell in row["cells"]
        )

    signatures = Counter(signature(row) for row in rows)
    modal = signatures.most_common(1)[0][0]
    matching = [row for row in rows if signature(row) == modal]
    if not matching:
        return None

    heights: Counter[float] = Counter()
    shapes: dict[tuple[int, int], Counter[str]] = {}
    attributes: dict[tuple[int, int], dict[str, Any]] = {}
    for row in matching:
        heights[round(float(row["height_pt"]), 2)] += 1
        for cell in row["cells"]:
            key = (int(cell["column"]), int(cell.get("colspan", 1) or 1))
            attributes.setdefault(key, cell)
            lines = cell.get("lines") or []
            if not lines:
                continue
            line = lines[0]
            runs = line.get("runs") or []
            shape = {
                "classes": cell.get("classes", []),
                "align": cell.get("align", "left"),
                "pad_left": cell.get("pad_left", 0.0),
                "pad_right": cell.get("pad_right", 0.0),
                "line_class": line.get("class", "t0"),
                "top_pt": line.get("top_pt", 0.0),
                "rotation": line.get("rotation", 0),
                "run_class": runs[0].get("class", line.get("class", "t0")) if runs else
                line.get("class", "t0"),
            }
            shapes.setdefault(key, Counter())[json.dumps(shape, sort_keys=True)] += 1

    if not heights or not shapes:
        return None

    common = Counter()
    for bucket in shapes.values():
        common.update(bucket)
    borrowed = json.loads(common.most_common(1)[0][0])

    cells: list[dict[str, Any]] = []
    for column, colspan in modal:
        bucket = shapes.get((column, colspan))
        if bucket is not None:
            shape = json.loads(bucket.most_common(1)[0][0])
        else:
            # Never observed with text. Keep the measured cell's own geometry and borrow the
            # band's most common text shape, so the column can still carry a value.
            cell = attributes[(column, colspan)]
            shape = borrowed | {
                "classes": cell.get("classes", []),
                "align": cell.get("align", "left"),
                "pad_left": cell.get("pad_left", 0.0),
                "pad_right": cell.get("pad_right", 0.0),
            }
        cells.append(shape | {"column": column, "colspan": colspan})

    return {"row_height_pt": heights.most_common(1)[0][0], "cells": cells}


def _aligned_column(source_edges: list[float], target_edges: list[float],
                    index: int) -> int | None:
    """The index in ``target_edges`` of the edge at ``source_edges[index]``, if they coincide."""
    if index >= len(source_edges):
        return None
    edge = source_edges[index]
    for position, value in enumerate(target_edges):
        if abs(value - edge) < 0.05:
            return position
    return None


def _value_columns(front_widths: list[float], body_widths: list[float],
                   cells: list[dict[str, Any]]) -> list[int] | None:
    """Which body column supplies each front-grid cell's value.

    A caller's row is positional on the *body* grid, because that is the grid ``header.labels``
    describes. A compound first page places the same values on its own finer grid, so each of its
    cells has to be traced back to the body column covering the same measured span. Both grids
    come from the measurement, so this is a lookup, not an estimate.

    Returns ``None`` if any cell does not line up, so a page whose grid is not a subdivision of
    the body grid is refused rather than approximated.
    """
    front_edges = _column_edges(front_widths)
    body_edges = _column_edges(body_widths)
    sources: list[int] = []
    for cell in cells:
        column = int(cell["column"])
        colspan = int(cell.get("colspan", 1) or 1)
        left = _aligned_column(front_edges, body_edges, column)
        right = _aligned_column(front_edges, body_edges, min(column + colspan,
                                                            len(front_edges) - 1))
        if left is None or right is None or right <= left:
            return None
        sources.append(left)
    return sources


def _body_to_front_columns(front_widths: list[float],
                           body_widths: list[float]) -> list[int] | None:
    """Each body column's index on the front grid, so an override keeps addressing body columns."""
    front_edges = _column_edges(front_widths)
    body_edges = _column_edges(body_widths)
    mapping: list[int] = []
    for index in range(len(body_widths)):
        position = _aligned_column(body_edges, front_edges, index)
        if position is None:
            return None
        mapping.append(position)
    return mapping


def _front_matter(page: dict[str, Any], body_widths: list[float]) -> dict[str, Any] | None:
    """Everything a compound first page carries above its data rows, kept as measured.

    ``_transplanted_header`` reduces such a page to two rows — the letterhead and the label row —
    and discards whatever sits between them. For ``school-results`` that is the division summary
    table, for the primary equivalent the grade matrix and the school's averages and ranks. Those
    bands are measured structure and belong in the package; only the *data* rows are the caller's.

    The bands cannot be moved onto the body grid: their cell boundaries are not edges of it, which
    is why :func:`_remap_row` refuses them. They are therefore kept on page 1's own grid, which
    ``document.py`` already supports because it validates ``columns`` per page.

    Returns ``None`` when the page carries nothing but a letterhead and a label row, since the
    existing two-row transplant is already faithful in that case.
    """
    rows = page["rows"]
    label_index = next((index for index, row in enumerate(rows) if _is_label_row(row)), None)
    if label_index is None or label_index < 1:
        return None

    band = [deepcopy(row) for row in rows[: label_index + 1]]
    widths = [float(width) for width in page["columns"]]
    height = sum(float(row["height_pt"]) for row in band)
    prototype = _spanning_prototype(rows[label_index + 1 :])
    sources = _value_columns(widths, body_widths, prototype["cells"]) if prototype else None
    columns_map = _body_to_front_columns(widths, body_widths)

    return {
        "columns": widths,
        "row_count": len(band),
        "rows": band,
        "height_pt": round(height, 3),
        # The reference's own page-1 capacity. Measured, so it needs no deriving.
        "data_rows": len(rows) - len(band),
        "table": {
            "x_pt": float(page["table_x_pt"]),
            "y_pt": float(page["table_y_pt"]),
            "width_pt": float(page["table_width_pt"]),
        },
        "rule": _hairline(page.get("rules") or [], float(page["table_y_pt"]), height),
        "vectors": page.get("vectors") or [],
        "loose_lines": page.get("loose_lines") or [],
        "body": prototype if sources else None,
        "value_columns": sources,
        "body_to_front_column": columns_map,
        # Which header-band row each front row corresponds to, so a `header` override written
        # against the transplanted band still lands: row 0 is the letterhead, the last is the
        # label row.
        "header_row_map": [0, len(band) - 1],
    }


def _column_fields(level: str, report_key: str, labels: list[str]) -> list[str] | None:
    """The field name of each measured column, from ``catalog/bindings.yaml``.

    Column identity belongs beside the measurement that established the columns. Without it every
    consumer has to retype the order of a 38-column grid and guard it with its own self-check,
    which is exactly what backend-sis had to do. Returns ``None`` when the catalogue has no entry,
    so an unmapped report says so in the data instead of shipping a guess.
    """
    catalogue = _bindings_catalogue()
    fields = catalogue.get(f"{level}/{report_key}")
    if fields is None:
        return None
    if len(fields) != len(labels):
        raise ValueError(
            f"{level}/{report_key}: catalog/bindings.yaml lists {len(fields)} columns but the "
            f"measured grid has {len(labels)}. Fix the catalogue or the grid; do not pad here."
        )
    return list(fields)


@lru_cache(maxsize=1)
def _bindings_catalogue() -> dict[str, list[str]]:
    if not BINDINGS_CATALOG.exists():
        return {}
    payload = yaml.safe_load(BINDINGS_CATALOG.read_text(encoding="utf-8")) or {}
    return dict(payload.get("reports") or {})


def _multi_block_reports() -> set[str]:
    """Reports whose pages carry several blocks of rows, each repeating the label band.

    Declared in ``catalog/bindings.yaml`` rather than detected, because detection is exactly what
    this project has repeatedly got wrong: every content-based attempt to tell a band from a body
    misclassified some page (see ``docs/06-exametrics-alignment.md`` §6). The reports that need it
    were established by measuring their label-row positions and data-row counts, and the declaration
    records that measurement so the build has no judgement to make.

    Applying the multi-block walk to every report was measured and rejected: it pulled label rows and
    second header tiers into the data plan on ``council_top_schools_alama``, ``council_top_schools_grading``,
    ``region_shule_serikali`` and five others, because those reports stack two header tiers whose
    upper row mixes column labels with subject names and so matches neither test.
    """
    if not BINDINGS_CATALOG.exists():
        return set()
    payload = yaml.safe_load(BINDINGS_CATALOG.read_text(encoding="utf-8")) or {}
    return set(payload.get("multi_block") or [])


def _table_grid_overrides() -> dict[str, int]:
    """The column count of the report's own table, where page count cannot establish it.

    ``distil_layout`` picks the grid most pages are measured on. That is right whenever the table
    occupies most of the report, and wrong when a report's further sections outnumber its table:
    ``region_ufaulu_masomo`` is one page of 28-column subject rows followed by two pages of
    20-column compound summaries, so the majority grid is the sections' and the distilled layout
    describes a table the rows do not belong to — its ``header.labels`` came out as 20 empty strings.

    Counting rows instead of pages does not fix it and was measured: the two summary pages carry 13
    rows spanning their full 20-column grid against page 1's 7, so row counts choose the sections
    too. No count separates them, which is why this is declared.
    """
    if not BINDINGS_CATALOG.exists():
        return {}
    payload = yaml.safe_load(BINDINGS_CATALOG.read_text(encoding="utf-8")) or {}
    return {key: int(value) for key, value in (payload.get("table_grid") or {}).items()}


def _repeating_size(report: dict[str, Any], pages: list[dict[str, Any]]) -> int:
    """The column count of the grid this report's table repeats on."""
    override = _table_grid_overrides().get(f"{report['level']}/{report['report_key']}")
    if override is not None:
        return override
    return Counter(len(page["columns"]) for page in pages).most_common(1)[0][0]



# ── Redistributable font substitution ─────────────────────────────────────────
#
# The reference PDFs embed subsets of proprietary faces, and `tools/extract.py` lifts those subsets
# out for local fidelity work. Embedding a subset in a PDF is ordinarily permitted by those licences;
# redistributing the extracted files inside a software package is a different act and is not covered
# by this project's MIT licence (docs/05-packaging.md). So the package ships none of them, and every
# text class that named one is repointed at an OFL face with the same metrics.
#
# MEASURED 2026-09-23, per character, over each subset's own cmap: twelve of the thirteen faces
# substitute EXACTLY — 0.0000 pt on every character. The Arial subsets differ on eight characters
# each (U+0640 tatweel and the U+2070–2079 superscript digits), and the corpus uses 73 distinct
# characters with a highest codepoint of U+2019, so none of them occurs anywhere in the 46 reports.
#
# Tahoma is the exception: it has no metric-compatible OFL clone, and 36 of its 39 characters differ
# by up to 0.7852 pt against Liberation Sans Bold. It backs ONE text class in ONE report, and a host
# with Tahoma installed still uses the real face because the CSS names it first.
_LIBERATION = "liberation"
_FONT_SUBSTITUTES: dict[str, str] = {
    # Arial → Liberation Sans (exact over every character the corpus uses)
    "CIDFont-F1-11.ttf": "liberation-sans-regular.ttf",
    "CIDFont-F3-27.ttf": "liberation-sans-regular.ttf",
    "CIDFont-F2-19.ttf": "liberation-sans-bold.ttf",
    "CIDFont-F4-35.ttf": "liberation-sans-bold.ttf",
    # Arial Narrow → Liberation Sans Narrow Bold (0.0000 pt)
    "BCDEEE-ArialNarrow-Bold-7.ttf": "liberation-sans-narrow-bold.ttf",
    "BCDEEE-ArialNarrow-Bold-10.ttf": "liberation-sans-narrow-bold.ttf",
    "BCDEEE-ArialNarrow-Bold-12.ttf": "liberation-sans-narrow-bold.ttf",
    "BCDEEE-ArialNarrow-Bold-14.ttf": "liberation-sans-narrow-bold.ttf",
    "BCDFEE-ArialNarrow-Bold-42.ttf": "liberation-sans-narrow-bold.ttf",
    "CIDFont-F4-36.ttf": "liberation-sans-narrow-bold.ttf",
    # Calibri → Carlito (0.0000 pt)
    "BCDFEE-Calibri-14.ttf": "carlito-regular.ttf",
    "CIDFont-F5-43.ttf": "carlito-bold.ttf",
    # Tahoma → Liberation Sans Bold. Not metric-identical; see above.
    "BCDEEE-Tahoma-Bold-14.ttf": "liberation-sans-bold.ttf",
}


def _substitute_css_fonts(css: str) -> tuple[str, list[str]]:
    """Repoint every ``@font-face`` src at a redistributable face.

    The per-report CSS declares one ``@font-face`` per embedded subset,
    ``src: url('fonts/<name>.ttf')``. Those files are not shipped, so leaving the rule alone makes
    WeasyPrint fall back silently — the text still renders, at the wrong widths, with nothing said.
    Rewriting the URL keeps the declared family name, which the HTML references, and swaps the file.

    Quote-agnostic on purpose: the generated CSS uses single quotes and an earlier version of this
    function only matched double ones, so it replaced nothing and reported nothing. That is precisely
    the silent fallback it exists to prevent.
    """
    unmapped: list[str] = []

    def replace(match: re.Match[str]) -> str:
        quote, name = match.group(1), match.group(2)
        if name.startswith("report-"):
            return match.group(0)
        replacement = _FONT_SUBSTITUTES.get(name)
        if replacement is None:
            unmapped.append(name)
            return match.group(0)
        return f"url({quote}../../_shared/fonts/{replacement}{quote})"

    out = re.sub(r"""url\((["'])fonts/([^"')]+)\1\)""", replace, css)
    return out, unmapped


def _substitute_fonts(layout: dict[str, Any]) -> list[str]:
    """Repoint every text class at a redistributable face, in place.

    Returns the faces that had no substitute, which is a build error rather than something to ship
    quietly: a missing file makes ``table._style_font`` fall back to base-14 without a word, and
    base-14 is not metric-compatible with Arial Narrow — the silent cost there is ~14 pt.
    """
    unmapped: list[str] = []
    for style in (layout.get("text_styles") or {}).values():
        relative = style.get("fontfile")
        if not relative:
            continue
        name = relative.rsplit("/", 1)[-1]
        replacement = _FONT_SUBSTITUTES.get(name)
        if replacement is None:
            unmapped.append(name)
            continue
        style["fontfile"] = f"../../_shared/fonts/{replacement}"
    return unmapped


def distil_layout(report: dict[str, Any], fixture: dict[str, Any], css: str) -> dict[str, Any]:
    """Reduce a measured fixture to the layout a caller's data can be placed onto."""
    pages = fixture["pages"]
    # The grid the report repeats, not simply page 1's. A first page that carries a summary band
    # above the table is measured on the union of both grids, so its column set subdivides the one
    # the body rows sit on. Distilling that page's grid leaves `table.columns` describing a table
    # the rows do not belong to, and the labels come from the summary band instead of the table's
    # own. Where page 1 already uses the repeating grid — which is every single-grid report — this
    # is exactly the previous behaviour.
    grid_sizes: Counter[int] = Counter(len(page["columns"]) for page in pages)
    repeating_size = _repeating_size(report, pages)
    if repeating_size not in grid_sizes:
        raise SystemExit(
            f"{report['level']}/{report['report_key']}: catalog/bindings.yaml declares a "
            f"{repeating_size}-column table grid, but no measured page has one "
            f"(measured: {dict(grid_sizes)})"
        )
    body_pages = [page for page in pages if len(page["columns"]) == repeating_size]
    compound_first_page = len(pages[0]["columns"]) != repeating_size

    if compound_first_page:
        first = body_pages[0]
        columns = [float(width) for width in first["columns"]]
        # The continuation pages' own `header_rows` marks a data row, because they carry no label
        # band; take the band from the page that does, and treat every row here as body.
        header = _transplanted_header(pages[0], columns)
        header_rows = len(header)
        body_skip = 0
    else:
        first = pages[0]
        header_rows = int(first["header_rows"])
        header = [dict(row) for row in first["rows"][:header_rows]]
        columns = [float(width) for width in first["columns"]]
        body_skip = header_rows

    prototype = _body_prototype(body_pages, body_skip)
    layout: dict[str, Any] = {
        "schema_version": LAYOUT_SCHEMA_VERSION,
        "level": report["level"],
        "report_key": report["report_key"],
        "title": fixture["report"].get("title", report.get("title", "")),
        "scope": report.get("scope", ""),
        "sample_unit": fixture["report"].get("sample_unit", ""),
        "page": {
            "width_pt": float(first["width_pt"]),
            "height_pt": float(first["height_pt"]),
            "orientation": first["orientation"],
        },
        "table": {
            "x_pt": float(first["table_x_pt"]),
            "y_pt": float(first["table_y_pt"]),
            "width_pt": float(first["table_width_pt"]),
            "columns": columns,
        },
        "header": {
            "row_count": header_rows,
            "rows": header,
            "height_pt": round(sum(float(row["height_pt"]) for row in header), 3),
            "labels": _column_labels(header, len(columns)),
            "fields": _column_fields(
                report["level"], report["report_key"], _column_labels(header, len(columns))
            ),
        },
        "text_styles": parse_text_styles(css),
        "rule": _hairline(
            first.get("rules") or [],
            float(first["table_y_pt"]),
            sum(float(row["height_pt"]) for row in header),
        ),
        "decorations": {
            "vectors": first.get("vectors") or [],
            "loose_lines": first.get("loose_lines") or [],
        },
        "measured_pages": len(pages),
    }
    if prototype:
        layout["body"] = prototype
        layout["rows_per_page"] = _rows_per_page(
            body_pages, body_skip, prototype["row_height_pt"]
        )
    else:
        # A report with no plain repeating body row (every band spans or is styled differently)
        # cannot be driven by the table API. Say so in the data rather than guessing a shape.
        layout["body"] = None
        layout["rows_per_page"] = 0

    if compound_first_page:
        front = _front_matter(pages[0], columns)
        if front is not None:
            layout["front"] = front

    # Page 1's own capacity, which is not the continuation pages' whenever page 1 carries a taller
    # band. Counted off the reference's own first page rather than derived, because the reference is
    # the authority on what it fitted — dividing the available height overshoots it.
    #
    # Only page 1 is measured here. A continuation page's capacity cannot be counted the same way:
    # `header_rows` on a continuation page marks a data row rather than a band, and several reports
    # are multi-section documents whose later pages start a new table with its own heading, so
    # "rows on the fullest later page" is not this table's capacity. `rows_per_page` therefore keeps
    # its previous derivation until that band classification is measured properly.
    front_band = layout.get("front")
    if front_band and front_band.get("body"):
        first_band_rows = int(front_band["row_count"])
    elif compound_first_page:
        # Page 1 could not be placed on its own grid, so it renders on the repeating grid behind
        # the transplanted band and its measured row count does not apply.
        first_band_rows = None
    else:
        first_band_rows = int(pages[0]["header_rows"])

    if first_band_rows is None:
        layout["first_page_rows"] = int(layout["rows_per_page"])
    else:
        layout["first_page_rows"] = max(1, len(pages[0]["rows"]) - first_band_rows)

    if prototype:
        row_height = float(prototype["row_height_pt"])
        band_height = float(
            front_band["height_pt"]
            if front_band and front_band.get("body")
            else layout["header"]["height_pt"]
        )
        bottom = float(layout["table"]["y_pt"]) + band_height + layout["first_page_rows"] * row_height
        if bottom > float(layout["page"]["height_pt"]) + 0.5:
            raise ValueError(
                f"{report['level']}/{report['report_key']}: page 1 would place "
                f"{layout['first_page_rows']} rows, ending at {bottom:.2f}pt on a "
                f"{layout['page']['height_pt']}pt page. The declared capacity does not fit the "
                "measured page box."
            )
    return layout


def _data_columns(layout: dict[str, Any]) -> set[int]:
    """The measured columns that carry a field name, i.e. the ones a caller's data replaces."""
    return {index for index, name in enumerate(layout["header"].get("fields") or []) if name}


def _cell_text(cell: dict[str, Any]) -> str:
    return "".join(
        "".join(run.get("text", "") for run in (line.get("runs") or []))
        for line in (cell.get("lines") or [])
    ).strip()


def _blank_corrections(node: Any) -> Any:
    """Empty every per-cluster advance correction in a subtree, keeping the key.

    ``document.py`` requires ``chunks`` on every run, so the key stays and only its contents go.
    The corrections describe one specific measured string, so on a row whose text a caller
    replaces they could never be valid.
    """
    if isinstance(node, dict):
        return {
            key: ([] if key == "chunks" else _blank_corrections(value))
            for key, value in node.items()
        }
    if isinstance(node, list):
        return [_blank_corrections(value) for value in node]
    return node


def _normalised(text: str) -> str:
    return " ".join(text.split()).casefold()


def _static_row(row: dict[str, Any], data_columns: set[int], label_texts: set[str],
                column_count: int) -> bool:
    """Whether a measured row is structure rather than data.

    Three things mark a row as structure, and none of them is its cell shape — shape varies between
    rows of the same table because a cell only exists where the reference printed something.

    1. It repeats the column labels. Continuation pages of most reports carry the label band again,
       and those cells sit in data columns, so without this they would be overwritten with values.
    2. It is a banner: one cell spanning most of the grid, which is how the letterhead and every
       section heading is measured.
    3. It puts text in only one data column while the table has several. A data row fills its row.
    """
    texts = [(int(cell["column"]), _cell_text(cell)) for cell in row["cells"]]
    filled = [(column, text) for column, text in texts if text]
    if not filled:
        return True

    for cell in row["cells"]:
        if int(cell.get("colspan", 1) or 1) >= max(2, column_count // 2) and _cell_text(cell):
            return True

    in_data = [(column, text) for column, text in filled if column in data_columns]
    if not in_data:
        return True
    if all(_normalised(text) in label_texts for _, text in in_data):
        return True
    return len(in_data) == 1 and len(data_columns) > 2


def _cell_texts_joined(row: dict[str, Any]) -> list[str]:
    """Each cell's text on one row, empties dropped."""
    out: list[str] = []
    for cell in row["cells"]:
        text = _cell_text(cell)
        if text:
            out.append(text)
    return out


def _label_rows(page: dict[str, Any], data_columns: set[int],
                label_texts: set[str]) -> list[int]:
    """Every row of the page that names the table's columns, in order.

    A summary band sits in the SAME columns as the table below it — ``school-results`` measures its
    division summary across the candidate table's own grid — so no test on a single row can tell the
    two apart. The reference separates them structurally: everything above the label row is front
    matter, everything below it is data.

    All matches are returned, not just one, because a page may carry several blocks of rows each
    repeating the label band. Measured: the four ``kimasomo`` / ``shule bora masomo`` reports print
    two or three ten-row blocks per page, one per subject, and a single-match rule marked only the
    last block's rows as data — 30 of their 60 rows.
    """
    found: list[int] = []
    for index, row in enumerate(page["rows"]):
        texts = [
            _cell_text(cell)
            for cell in row["cells"]
            if int(cell["column"]) in data_columns and _cell_text(cell)
        ]
        if len(texts) < 2:
            continue
        hits = sum(1 for text in texts if _normalised(text) in label_texts)
        if hits >= 2 and hits * 2 >= len(texts):
            found.append(index)
    return found


def _data_start(page: dict[str, Any], data_columns: set[int], label_texts: set[str],
                column_count: int, multi_block: bool) -> int:
    """The row where this page's data begins: past the leading header band, not past every band.

    The leading band is the run of label rows at the top of the page with nothing but structure
    between them, which is what a stacked header looks like. Scanning stops at the first label row
    that has data above it, because that row introduces a later block rather than the page's header.
    Those later label rows are excluded by :func:`_static_row` on the label-text test, so they are
    not mistaken for values.

    If the very first label row already has non-structure above it, no clean leading band exists and
    this falls back to the previous rule — the **last** label row on the page. That happens when the
    distilled ``header.labels`` is not a label row at all: ``council_school_rank_ufaulu_alama`` and
    ``council_kata_rank_alama`` both distilled a DATA row as their labels, so every data row matches
    and the walk cannot tell a band from a body. Falling back keeps those two exactly as they were
    rather than letting a known-bad measurement pull three header rows into the data plan.
    """
    rows = _label_rows(page, data_columns, label_texts)
    if not rows:
        return 0
    if not multi_block:
        return rows[-1] + 1
    start = 0
    advanced = False
    for index in rows:
        if index < start:
            continue
        if all(
            _static_row(page["rows"][between], data_columns, label_texts, column_count)
            or _header_tier(page["rows"][between])
            for between in range(start, index)
        ):
            start = index + 1
            advanced = True
        else:
            break
    if not advanced:
        return rows[-1] + 1
    return start


def _header_tier(row: dict[str, Any]) -> bool:
    """Whether a row is a tier of group headings rather than a row of values.

    Every filled cell spans more than one column, which is how the tier above the labels is measured
    (``WALIOSAJILIWA │ A │ B │ C │ D │ E │ A-D`` over the ``WAV/WAS/JML`` labels beneath). A data row
    fills individual columns, so at least one of its filled cells has colspan 1.

    This alone is not sufficient, and must only ever be applied to a row that sits directly above a
    label row — see :func:`_document_plan`. A trailing aggregate is measured with the same spans:
    ``region_halmashauri_masomo``'s ``ASILIMIA YA UFAULU`` row spans 6,3,3,3,3,3,3,4 and carries this
    exam's percentages. Excluding it on spans alone dropped it from the data plan, which would print
    the reference's own percentages verbatim.
    """
    spans = [int(cell.get("colspan", 1) or 1) for cell in row["cells"] if _cell_text(cell)]
    return len(spans) > 1 and all(span > 1 for span in spans)


# ── Cell roles ────────────────────────────────────────────────────────────────
#
# What each static cell IS, decided once here against the reference rather than by every consumer at
# runtime. backend-sis carries 407 lines doing this with regexes over the rendered string on every
# render, including SAMPLE_LOCATIONS = ("MWANZA CC", "MWANZA") hardcoded in the application — the
# sample's own identity, in the consumer. The measurement knows the answer, so it records it.
#
# Where a structural signal exists it is used. Where only the text can distinguish — which line of a
# letterhead is the region — the text is read once, here, and the verdict shipped.

ROLE_AUTHORITY = "authority"
ROLE_REGION = "region"
ROLE_EXAM = "exam"
ROLE_SCOPE = "scope"
ROLE_HEADING = "heading"
ROLE_FIGURE = "figure"
ROLE_SAMPLE = "sample"

# Fixed institutional text, reproduced unchanged. These open the letterhead at both levels — English
# on the secondary references, Swahili on the primary ones.
_AUTHORITY_PREFIXES: tuple[str, ...] = (
    "THE PRIME MINISTER",
    "OFISI YA WAZIRI MKUU",
    "REGIONAL ADMINISTRATION",
    "TAWALA ZA MIKOA",
)

# How the references word a region line. This is the documents' own grammar, not the sample's
# identity, so it is a legitimate rule rather than reference data.
_REGION_SUFFIX = " REGION"
_REGION_PREFIX = "MKOA WA "

# How the references name a results document.
_EXAM_MARKERS: tuple[str, ...] = ("RESULTS", "MATOKEO", "ASSESSMENT", "MTIHANI")

# A number, optionally decimal or a percentage.
_NUMERIC_VALUE = re.compile(r"^-?\d+(?:[.,]\d+)?%?$")

# A rank as the references write it — "48/64", "359 / 387", and "/521" where the numerator was not
# printed. A computed position, so it is data. Without this the ranking columns of
# school_results' subject analysis stayed headings and printed the reference school's positions.
_RANK_VALUE = re.compile(r"^\d*\s*/\s*\d+$")

# A competency band as the references spell it — "DARAJA B (VIZURI SANA)", "Grade C (Good)". Computed
# from the figures beside it, so it is data. The parenthesised band name is required: without it this
# also matches the column labels "DARAJA A-D" and "DARAJA E", and blanking those would delete
# headings the reference draws.
_COMPETENCY_VALUE = re.compile(r"^(?:grade|daraja)\s+[A-E]\s*\(", re.IGNORECASE)

# Figures a row must carry before it reads as a band of data. A lone integer is far more likely to be
# a column label — the division "0" heading — than a total.
_MIN_FIGURES_PER_ROW = 4

# Words that name the report rather than the unit it covers, so they cannot identify a scope line.
_TITLE_NOISE = frozenset({
    "MOCK", "RESULTS", "MATOKEO", "MTIHANI", "ASSESSMENT", "EXAMINATION", "FORM", "STANDARD",
    "REGIONAL", "REGION", "MKOA", "WA", "YA", "NA", "LA", "DARASA", "AND", "THE", "OF",
})


def _sample_tokens(fixture: dict[str, Any]) -> frozenset[str]:
    """The words that name the unit this report was measured from.

    Read from the fixture's own ``sample_unit`` — ``PS1304014-BUTIMBA PRIMARY SCHOOL`` — so the
    sample's identity comes from the measurement instead of being hardcoded in a consumer.

    The report's own ``title`` is subtracted, because ``sample_unit`` mixes the unit with the report
    name: ``Mwanza Top 10 Schools`` is a region plus a title. Without the subtraction, the heading
    ``TOP 10 BEST SCHOOLS OVERALL`` matched on ``TOP``/``SCHOOLS`` and was classified as the scope,
    which would have blanked a heading the reference draws. Measured on four reports.
    """
    report = fixture.get("report") or {}

    def words(value: Any) -> set[str]:
        return {
            token
            for token in re.split(r"[^A-Z0-9]+", str(value or "").upper())
            if len(token) > 2 and token not in _TITLE_NOISE and not token.isdigit()
        }

    return frozenset(words(report.get("sample_unit")) - words(report.get("title")))


def _identity_tokens(fixture: dict[str, Any]) -> frozenset[str]:
    """Every word that names the exam the report was measured from.

    ``sample_unit`` alone is not enough, and this was measured: ``region_shule_bora_jumla``'s is
    ``MKOA SHULE BORA STD4 JUMLA 2026``, which never names Mwanza, so the reference's
    ``MWANZA CC`` cells in its further sections could not be recognised and were published.

    The measurement itself knows better. A first pass classifies the letterhead with whatever
    ``sample_unit`` gives; every region line it finds is then stripped of the references' own wording
    and its remaining words unioned in. So ``MKOA WA MWANZA`` contributes ``MWANZA`` whether or not
    the sample unit mentions it.
    """
    tokens = set(_sample_tokens(fixture))
    for page in fixture["pages"]:
        lines: list[str] = []
        for row in page["rows"]:
            for cell in row["cells"]:
                lines.extend(_cell_line_texts(cell))
        for line in page.get("loose_lines") or []:
            lines.append("".join(run.get("text", "") for run in (line.get("runs") or [])))
        for text in lines:
            # Region lines only. A scope line mixes the unit with the report title
            # (`MWANZA CC TOP TEN BEST SCHOOLS`), and taking its words blanked real headings on six
            # reports — TOP, BEST and SCHOOLS appear in headings everywhere. A region line is just a
            # place name, so it is safe to read.
            if _line_role(text, frozenset(tokens)) != ROLE_REGION:
                continue
            value = text.upper().removeprefix(_REGION_PREFIX).removesuffix(_REGION_SUFFIX)
            tokens.update(
                token
                for token in re.split(r"[^A-Z0-9]+", value)
                if len(token) > 2 and token not in _TITLE_NOISE and not token.isdigit()
            )
    return frozenset(tokens)


def _line_role(text: str, sample: frozenset[str]) -> str:
    """What one line of a static band is."""
    value = (text or "").strip().upper()
    if not value:
        return ROLE_HEADING
    if any(value.startswith(prefix) for prefix in _AUTHORITY_PREFIXES):
        return ROLE_AUTHORITY
    if value.startswith(_REGION_PREFIX) or value.endswith(_REGION_SUFFIX):
        return ROLE_REGION
    if any(marker in value for marker in _EXAM_MARKERS):
        return ROLE_EXAM
    if any(token in value for token in sample):
        return ROLE_SCOPE
    return ROLE_HEADING


def _is_figure(text: str, figures_in_row: int) -> bool:
    """Whether a static cell holds a computed value rather than a label."""
    value = text.strip()
    if not value:
        return False
    if _COMPETENCY_VALUE.match(value):
        return True
    if _RANK_VALUE.match(value):
        return True
    if not _NUMERIC_VALUE.match(value):
        return False
    if figures_in_row >= _MIN_FIGURES_PER_ROW:
        return True
    return not value.isdigit()


def _is_letterhead(cell: dict[str, Any], column_count: int, lone: bool = False) -> bool:
    """Whether a cell is the letterhead rather than a heading or a value.

    The letterhead is the wide cell at column 0; a heading such as ``GRADE PERFORMANCE`` sits at an
    inner column and spans only its own group. ``region``, ``exam`` and ``scope`` exist *only* here,
    which matters: ``school_results`` page 14 has a label cell reading
    ``EXAMINATION CENTRE REGION``, and without this restriction the " REGION" suffix rule named that
    label the region — inviting a caller to overwrite a heading the reference draws. The value beside
    it is the region; the label is not.
    """
    return int(cell["column"]) == 0 and int(cell.get("colspan", 1) or 1) >= max(
        2, column_count // 2
    )


def _row_roles(row: dict[str, Any], sample: frozenset[str],
               column_count: int) -> dict[str, str]:
    """Roles for one static row, keyed ``"column"`` or ``"column.line"``.

    A cell with one line is named by its column. A cell holding several lines — a letterhead is one
    cell of six — gets a role per line, so each is individually addressable.
    """
    figures_in_row = sum(
        1
        for cell in row["cells"]
        for text in _cell_line_texts(cell)
        if _NUMERIC_VALUE.match(text.strip())
    )
    filled = [cell for cell in row["cells"] if any(t.strip() for t in _cell_line_texts(cell))]
    # A label paired with its value, which is how the compound summary sheets are measured:
    # `TOTAL PASSED CANDIDATES | 434`, `EXAMINATION CENTRE AVERAGE | 24.79  F`,
    # `EXAMINATION CENTRE RANKING COUNCILWISE | 58 / 64`. The numeric-density rule cannot see these —
    # one or two figures in a row is not a band — and `434`, `58 / 64` and `24.79  F` were left as
    # headings and therefore printed. Structural: in a short row led by a text cell, everything after
    # the first filled cell is that label's value, whatever its formatting.
    value_columns: set[int] = set()
    if 2 <= len(filled) <= 3:
        lead = " ".join(_cell_line_texts(filled[0])).strip()
        if lead and not _NUMERIC_VALUE.match(lead):
            value_columns = {int(cell["column"]) for cell in filled[1:]}

    out: dict[str, str] = {}
    for cell in row["cells"]:
        column = int(cell["column"])
        texts = _cell_line_texts(cell)
        if not texts:
            continue
        letterhead = _is_letterhead(cell, column_count) and (
            len(texts) > 1 or len(filled) == 1
        )
        for index, text in enumerate(texts):
            if column in value_columns or _is_figure(text, figures_in_row):
                role = ROLE_FIGURE
            elif letterhead:
                role = _line_role(text, sample)
            elif any(token in text.upper() for token in sample):
                # Reference identity outside the letterhead: a council or school name the reference
                # printed in a cell that is neither a letterhead line nor a figure. Found by the
                # identity audit in docs/06 — council_top_schools page 3 and the further sections of
                # region_shule_bora_jumla and region_council_performance each keep one. There is no
                # address a caller could fill it from, so it is named and blanked rather than
                # published.
                role = ROLE_SAMPLE
            else:
                role = ROLE_HEADING
            key = str(column) if len(texts) == 1 else f"{column}.{index}"
            out[key] = role
    return out


def _cell_line_texts(cell: dict[str, Any]) -> list[str]:
    """The measured text of each line in one cell, in order."""
    return [
        "".join(run.get("text", "") for run in (line.get("runs") or []))
        for line in (cell.get("lines") or [])
    ]


def _loose_roles(page: dict[str, Any], sample: frozenset[str]) -> dict[str, str]:
    """Roles for the absolutely-positioned lines some reports draw beside the table.

    Six of the 46 put their whole letterhead here rather than in a header band —
    ``council_subjects_rank``, ``council_schools_rank_subjectwise``, ``subject_schools_rank``,
    ``region_subjects_performance``, ``region_halmashauri_masomo`` and ``region_halmashauri_jumla`` —
    so without roles here those reports have no way to replace `MWANZA REGION` or the reference exam
    title. Keyed by line index, which is how the measured document stores them.
    """
    out: dict[str, str] = {}
    lines = page.get("loose_lines") or []
    figures = sum(
        1
        for line in lines
        if _NUMERIC_VALUE.match(
            "".join(run.get("text", "") for run in (line.get("runs") or [])).strip()
        )
    )
    for index, line in enumerate(lines):
        text = "".join(run.get("text", "") for run in (line.get("runs") or []))
        if not text.strip():
            continue
        out[str(index)] = (
            ROLE_FIGURE if _is_figure(text, figures) else _line_role(text, sample)
        )
    return out


def _document_roles(fixture: dict[str, Any], plan: list[list[int]]) -> list[dict[str, Any]]:
    """Roles for every static row of every page, in page order.

    Only rows the plan does not mark as data: a data row's content is the caller's and needs no role.
    Keyed ``"row.column"`` or ``"row.column.line"``, the same address space the ``bands`` overrides
    use, so a caller reads a role and writes to that address.
    """
    out: list[dict[str, Any]] = []
    sample = _identity_tokens(fixture)
    for page, data_rows in zip(fixture["pages"], plan):
        data = set(data_rows)
        column_count = len(page["columns"])
        roles: dict[str, str] = {}
        for row_index, row in enumerate(page["rows"]):
            if row_index in data:
                continue
            for key, role in _row_roles(row, sample, column_count).items():
                roles[f"{row_index}.{key}"] = role
        out.append(roles)
    return out


def _document_loose_roles(fixture: dict[str, Any]) -> list[dict[str, str]]:
    sample = _identity_tokens(fixture)
    return [_loose_roles(page, sample) for page in fixture["pages"]]


def _document_plan(fixture: dict[str, Any], layout: dict[str, Any]) -> list[list[int]]:
    """Which rows of each measured page carry data, decided once at build time.

    Deciding this here rather than at render time matters: the build can be reviewed against the
    reference, and the runtime then has no judgement to make and no way to mistake a heading — or a
    summary band sharing the table's columns — for a row of values.
    """
    data_columns = _data_columns(layout)
    multi_block = f"{layout['level']}/{layout['report_key']}" in _multi_block_reports()
    label_texts = {
        _normalised(label) for label in (layout["header"].get("labels") or []) if label.strip()
    }
    # Only pages on the grid this layout describes. A report can print further sections on their
    # own grids — school-results ends with a 24-column division summary and a 22-column subject
    # analysis — and those are different tables whose rows are not the caller's. Their label rows
    # do not match this table's labels, so without this they are taken for data and overwritten.
    plan: list[list[int]] = []
    # Which pages are this table's. Not decided by inspecting row content — whether a row looks
    # like a label or a value depends on what the reference happened to print, and three different
    # content tests each got it wrong on some page. The grid decides it, exactly as distil_layout
    # already decides which grid to distil: the table's pages are the ones on the repeating grid,
    # plus the first page when it is measured on its own compound grid. Anything else is a further
    # section the report prints whole — school-results ends with a 24-column division summary and a
    # 22-column subject analysis — and those are carried verbatim.
    sizes: Counter[int] = Counter(len(page["columns"]) for page in fixture["pages"])
    declared = _table_grid_overrides().get(f"{layout['level']}/{layout['report_key']}")
    repeating = declared if declared is not None else sizes.most_common(1)[0][0]
    table_sizes = {repeating, len(fixture["pages"][0]["columns"])}
    if declared is not None:
        # A declared grid also declares what is NOT the table: page 1 is only included when it is
        # measured on that grid, otherwise the sections would be taken for data.
        table_sizes = {repeating}
    for page in fixture["pages"]:
        columns = len(page["columns"])
        if columns not in table_sizes:
            plan.append([])
            continue
        start = _data_start(page, data_columns, label_texts, columns, multi_block)
        # A multi-block page repeats its header above every block, so those tiers appear after the
        # page's leading band and must be excluded here rather than by a test on the row alone.
        # Restricting the rule to a row directly above a label row is what keeps a trailing
        # aggregate — measured with the same spans — in the data plan.
        labels = set(_label_rows(page, data_columns, label_texts))
        tiers = {
            index
            for index in range(len(page["rows"]))
            if index + 1 in labels and _header_tier(page["rows"][index])
        }
        plan.append(
            [
                index
                for index, row in enumerate(page["rows"])
                if index >= start
                and index not in tiers
                and index not in labels
                and not _static_row(row, data_columns, label_texts, columns)
            ]
        )
    return plan


def prepare_document(fixture: dict[str, Any], layout: dict[str, Any]) -> dict[str, Any]:
    """The measured document a caller's data is substituted into.

    This is the fixture itself, not a reduction of it: every band, every per-page column grid,
    every measured rule and vector and every page of a multi-section report is carried as
    measured. Two things change. The per-cluster corrections are emptied on the data rows, because
    those rows get new text and the corrections describe the old string. And each page records
    which of its rows are data, so the renderer follows a plan settled here against the reference
    instead of inferring one.

    Static text keeps its corrections and therefore its per-glyph fidelity.
    """
    document = deepcopy(fixture)
    data_columns = _data_columns(layout)
    plan = _document_plan(fixture, layout)
    roles = _document_roles(fixture, plan)
    loose = _document_loose_roles(fixture)
    for page, rows, page_roles, page_loose in zip(document["pages"], plan, roles, loose):
        page["data_rows"] = rows
        page["roles"] = page_roles
        if page_loose:
            page["loose_roles"] = page_loose
        for index in rows:
            row = page["rows"][index]
            row["cells"] = [
                _blank_corrections(cell) if int(cell["column"]) in data_columns else cell
                for cell in row["cells"]
            ]
    return document


def write_document(destination: Path, document: dict[str, Any]) -> None:
    """Write the measured document, compressed.

    Uncompressed the 46 come to 36 MB, which is why shipping geometry looked impossible; gzipped
    they are about 2 MB, against 3.85 MB for the distilled layouts. ``gzip`` is in the standard
    library, so this adds no dependency.
    """
    payload = json.dumps(document, separators=(",", ":"), sort_keys=True).encode("utf-8")
    with gzip.GzipFile(destination, "wb", compresslevel=9, mtime=0) as handle:
        handle.write(payload)


def _sync_tree(source: Path, destination: Path) -> None:
    """Mirror one directory of files, pruning anything the source no longer has.

    Pruning matters: without it a file deleted from the workshop stayed in the committed resources
    for ever, and `make check-resources` could not see it because it only compares the files the
    source still names. Two extracted proprietary faces survived exactly that way.
    """
    destination.mkdir(parents=True, exist_ok=True)
    wanted: set[str] = set()
    for child in sorted(source.iterdir()):
        if child.is_dir():
            continue
        wanted.add(child.name)
        target = destination / child.name
        if not target.exists() or not filecmp.cmp(child, target, shallow=False):
            shutil.copy2(child, target)
    for existing in sorted(destination.iterdir()):
        if existing.is_file() and existing.name not in wanted:
            existing.unlink()


def build(check: bool = False) -> list[str]:
    """Regenerate every packaged resource. Returns a list of human-readable differences.

    With ``check=True`` nothing is written and the differences are reported instead, so the test
    suite can fail when the committed resources have drifted from the workshop.
    """
    if check:
        return _check()

    catalog = load_catalog()
    reports = catalog["reports"]
    RESOURCE_DIR.mkdir(parents=True, exist_ok=True)

    # One template for all 46. Assert that before relying on it.
    templates = {
        (template_dir(report) / "template.html").read_bytes()
        for report in reports
        if (template_dir(report) / "template.html").exists()
    }
    if len(templates) != 1:
        raise RuntimeError(
            f"Expected one shared template.html across all reports, found {len(templates)} "
            "distinct versions. The package ships a single copy, so they must not diverge."
        )
    (RESOURCE_DIR / "template.html").write_bytes(templates.pop())

    (RESOURCE_DIR / "_shared").mkdir(parents=True, exist_ok=True)
    shutil.copy2(SHARED_SOURCE / "reset.css", RESOURCE_DIR / "_shared" / "reset.css")
    _sync_tree(SHARED_SOURCE / "fonts", RESOURCE_DIR / "_shared" / "fonts")

    registry = {
        "schema_version": 1,
        "sources": catalog.get("sources", {}),
        "reports": [
            {
                "ordinal": report["ordinal"],
                "level": report["level"],
                "report_key": report["report_key"],
                "title": report["title"],
                "scope": report["scope"],
                "sample_unit": report.get("sample_unit", ""),
            }
            for report in sorted(reports, key=lambda item: item["ordinal"])
        ],
    }
    write_json(RESOURCE_DIR / "reports.json", registry)

    for report in reports:
        source = template_dir(report)
        destination = RESOURCE_DIR / report["level"] / artifact_name(report["report_key"])
        destination.mkdir(parents=True, exist_ok=True)

        css_path = source / "report.css"
        css_text, css_unmapped = _substitute_css_fonts(
            css_path.read_text(encoding="utf-8"))
        if css_unmapped:
            raise SystemExit(
                f"{report['level']}/{report['report_key']}: report.css still names "
                f"{sorted(set(css_unmapped))}, which is not shipped. Add it to _FONT_SUBSTITUTES."
            )
        (destination / "report.css").write_text(css_text, encoding="utf-8")
        # Per-report `fonts/` are NOT shipped: they hold subsets extracted from the reference PDFs,
        # several derived from proprietary faces. `_substitute_fonts` repoints every text class at a
        # redistributable OFL face in `_shared/fonts` instead.
        stale = destination / "fonts"
        if stale.is_dir():
            shutil.rmtree(stale)

        fixture_path = source / "fixture.json"
        if not fixture_path.exists():
            continue
        fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
        layout = distil_layout(report, fixture, css_path.read_text(encoding="utf-8"))
        unmapped = _substitute_fonts(layout)
        if unmapped:
            raise SystemExit(
                f"{report['level']}/{report['report_key']}: no redistributable substitute for "
                f"{sorted(set(unmapped))}. Add one to _FONT_SUBSTITUTES with its measured advance "
                "delta, or the class silently falls back to base-14."
            )
        write_json(destination / "layout.json", layout)
        write_document(destination / "document.json.gz", prepare_document(fixture, layout))

    return []


def _check() -> list[str]:
    """Rebuild into a scratch tree and diff it against the committed resources."""
    import tempfile

    global RESOURCE_DIR
    committed = RESOURCE_DIR
    with tempfile.TemporaryDirectory(prefix="mussannoni-resource-check-") as raw:
        RESOURCE_DIR = Path(raw) / "resources"
        try:
            build(check=False)
            fresh = RESOURCE_DIR
        finally:
            RESOURCE_DIR = committed

        differences: list[str] = []
        fresh_files = {p.relative_to(fresh) for p in fresh.rglob("*") if p.is_file()}
        committed_files = {
            p.relative_to(committed) for p in committed.rglob("*") if p.is_file()
        }
        for missing in sorted(fresh_files - committed_files):
            differences.append(f"missing from package resources: {missing}")
        for extra in sorted(committed_files - fresh_files):
            differences.append(f"stale in package resources: {extra}")
        for shared in sorted(fresh_files & committed_files):
            if not filecmp.cmp(fresh / shared, committed / shared, shallow=False):
                differences.append(f"out of date in package resources: {shared}")
        return differences


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the committed package resources are current, writing nothing",
    )
    args = parser.parse_args()

    differences = build(check=args.check)
    if args.check:
        if differences:
            print(f"package resources are out of date ({len(differences)} differences):")
            for difference in differences[:20]:
                print(f"  {difference}")
            if len(differences) > 20:
                print(f"  ... and {len(differences) - 20} more")
            raise SystemExit(1)
        print("package resources are current")
    else:
        count = sum(1 for _ in RESOURCE_DIR.rglob("*") if _.is_file())
        print(f"synced {count} files into {RESOURCE_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
